### ISSUE TITLE
A Long Time Ago file appears blank in-game

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/treasure-disks#1]
When I open the data pack ZIP, I find the file at "\data\computercraft\lua\treasure\dan200\alongtimeago\", but when I try to run "disk/alongtimeago", I get the following error:

<code>bios.lua:503: bad argument #1 to 'load' (expected function or string, got nil)</code>

I tested the program by hacking a player-crafted disk, and it runs great, especially on huge monitors! It's just not possible to run with the actual treasure disk.

**Comment by SquidDev** [comment]
Fixed in https://github.com/SquidDev-CC/CC-Tweaked/commit/1fecb995c909b32a65c9337623b03c635cd2f2d3.
